"""update

Revision ID: 0168b2379592
Revises: 839d2afbfbf7
Create Date: 2026-04-08 19:19:00.394204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0168b2379592'
down_revision: Union[str, Sequence[str], None] = '839d2afbfbf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('style', sa.String(), nullable=True))
    op.drop_column('cards', 'card_style')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('card_style', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('cards', 'style')
    # ### end Alembic commands ###
