"""update

Revision ID: 839d2afbfbf7
Revises: d33c23d48306
Create Date: 2026-04-06 20:42:40.792940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '839d2afbfbf7'
down_revision: Union[str, Sequence[str], None] = 'd33c23d48306'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('card_style', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'card_style')
    # ### end Alembic commands ###
