"""change_style_to_json

Revision ID: b7220d58a530
Revises: 25bbebbf90fb
Create Date: 2026-04-15 13:14:48.547317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7220d58a530'
down_revision: Union[str, Sequence[str], None] = '25bbebbf90fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


from sqlalchemy.dialects import postgresql

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cards', 'style',
               existing_type=sa.VARCHAR(),
               type_=postgresql.JSONB(),
               postgresql_using="style::jsonb",
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cards', 'style',
               existing_type=postgresql.JSONB(),
               type_=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
