"""update

Revision ID: d33c23d48306
Revises: 072508fafdf5
Create Date: 2026-03-28 12:28:02.745475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd33c23d48306'
down_revision: Union[str, Sequence[str], None] = '072508fafdf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'current_card',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'current_card',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
