"""update

Revision ID: e88fd052f423
Revises: 
Create Date: 2026-03-23 16:16:42.740901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e88fd052f423'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.String(length=2048), nullable=True))
    op.add_column('users', sa.Column('theme', sa.String(length=50), server_default='default', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'theme')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###
